// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: STTMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;

namespace AgoraSTTSample.Protobuf {

  /// <summary>Holder for reflection information generated from STTMessage.proto</summary>
  public static partial class STTMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for STTMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static STTMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBTVFRNZXNzYWdlLnByb3RvEhFBZ29yYS5BdWRpb1RvVGV4dCK6AQoEVGV4",
            "dBIOCgZ2ZW5kb3IYASABKAUSDwoHdmVyc2lvbhgCIAEoBRIOCgZzZXFudW0Y",
            "AyABKAUSCwoDdWlkGAQgASgFEgwKBGZsYWcYBSABKAUSDAoEdGltZRgGIAEo",
            "AxIMCgRsYW5nGAcgASgFEhEKCXN0YXJ0dGltZRgIIAEoBRIPCgdvZmZ0aW1l",
            "GAkgASgFEiYKBXdvcmRzGAogAygLMhcuQWdvcmEuQXVkaW9Ub1RleHQuV29y",
            "ZCJhCgRXb3JkEgwKBHRleHQYASABKAkSEAoIc3RhcnRfbXMYAiABKAUSEwoL",
            "ZHVyYXRpb25fbXMYAyABKAUSEAoIaXNfZmluYWwYBCABKAgSEgoKY29uZmlk",
            "ZW5jZRgFIAEoAUIaqgIXQWdvcmFTVFRTYW1wbGUuUHJvdG9idWZiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AgoraSTTSample.Protobuf.Text), global::AgoraSTTSample.Protobuf.Text.Parser, new[]{ "Vendor", "Version", "Seqnum", "Uid", "Flag", "Time", "Lang", "Starttime", "Offtime", "Words" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AgoraSTTSample.Protobuf.Word), global::AgoraSTTSample.Protobuf.Word.Parser, new[]{ "Text", "StartMs", "DurationMs", "IsFinal", "Confidence" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Text : pb::IMessage<Text>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Text> _parser = new pb::MessageParser<Text>(() => new Text());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Text> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgoraSTTSample.Protobuf.STTMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Text() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Text(Text other) : this() {
      vendor_ = other.vendor_;
      version_ = other.version_;
      seqnum_ = other.seqnum_;
      uid_ = other.uid_;
      flag_ = other.flag_;
      time_ = other.time_;
      lang_ = other.lang_;
      starttime_ = other.starttime_;
      offtime_ = other.offtime_;
      words_ = other.words_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Text Clone() {
      return new Text(this);
    }

    /// <summary>Field number for the "vendor" field.</summary>
    public const int VendorFieldNumber = 1;
    private int vendor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Vendor {
      get { return vendor_; }
      set {
        vendor_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "seqnum" field.</summary>
    public const int SeqnumFieldNumber = 3;
    private int seqnum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Seqnum {
      get { return seqnum_; }
      set {
        seqnum_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 4;
    private int uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "flag" field.</summary>
    public const int FlagFieldNumber = 5;
    private int flag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Flag {
      get { return flag_; }
      set {
        flag_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 6;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "lang" field.</summary>
    public const int LangFieldNumber = 7;
    private int lang_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Lang {
      get { return lang_; }
      set {
        lang_ = value;
      }
    }

    /// <summary>Field number for the "starttime" field.</summary>
    public const int StarttimeFieldNumber = 8;
    private int starttime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Starttime {
      get { return starttime_; }
      set {
        starttime_ = value;
      }
    }

    /// <summary>Field number for the "offtime" field.</summary>
    public const int OfftimeFieldNumber = 9;
    private int offtime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Offtime {
      get { return offtime_; }
      set {
        offtime_ = value;
      }
    }

    /// <summary>Field number for the "words" field.</summary>
    public const int WordsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::AgoraSTTSample.Protobuf.Word> _repeated_words_codec
        = pb::FieldCodec.ForMessage(82, global::AgoraSTTSample.Protobuf.Word.Parser);
    private readonly pbc::RepeatedField<global::AgoraSTTSample.Protobuf.Word> words_ = new pbc::RepeatedField<global::AgoraSTTSample.Protobuf.Word>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AgoraSTTSample.Protobuf.Word> Words {
      get { return words_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Text);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Text other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Vendor != other.Vendor) return false;
      if (Version != other.Version) return false;
      if (Seqnum != other.Seqnum) return false;
      if (Uid != other.Uid) return false;
      if (Flag != other.Flag) return false;
      if (Time != other.Time) return false;
      if (Lang != other.Lang) return false;
      if (Starttime != other.Starttime) return false;
      if (Offtime != other.Offtime) return false;
      if(!words_.Equals(other.words_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Vendor != 0) hash ^= Vendor.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (Seqnum != 0) hash ^= Seqnum.GetHashCode();
      if (Uid != 0) hash ^= Uid.GetHashCode();
      if (Flag != 0) hash ^= Flag.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (Lang != 0) hash ^= Lang.GetHashCode();
      if (Starttime != 0) hash ^= Starttime.GetHashCode();
      if (Offtime != 0) hash ^= Offtime.GetHashCode();
      hash ^= words_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Vendor != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Vendor);
      }
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Version);
      }
      if (Seqnum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seqnum);
      }
      if (Uid != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Uid);
      }
      if (Flag != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Flag);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Lang != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Lang);
      }
      if (Starttime != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Starttime);
      }
      if (Offtime != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Offtime);
      }
      words_.WriteTo(output, _repeated_words_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Vendor != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Vendor);
      }
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Version);
      }
      if (Seqnum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seqnum);
      }
      if (Uid != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Uid);
      }
      if (Flag != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Flag);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Lang != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Lang);
      }
      if (Starttime != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Starttime);
      }
      if (Offtime != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Offtime);
      }
      words_.WriteTo(ref output, _repeated_words_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Vendor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Vendor);
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      if (Seqnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seqnum);
      }
      if (Uid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Uid);
      }
      if (Flag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Flag);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (Lang != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lang);
      }
      if (Starttime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Starttime);
      }
      if (Offtime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offtime);
      }
      size += words_.CalculateSize(_repeated_words_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Text other) {
      if (other == null) {
        return;
      }
      if (other.Vendor != 0) {
        Vendor = other.Vendor;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.Seqnum != 0) {
        Seqnum = other.Seqnum;
      }
      if (other.Uid != 0) {
        Uid = other.Uid;
      }
      if (other.Flag != 0) {
        Flag = other.Flag;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.Lang != 0) {
        Lang = other.Lang;
      }
      if (other.Starttime != 0) {
        Starttime = other.Starttime;
      }
      if (other.Offtime != 0) {
        Offtime = other.Offtime;
      }
      words_.Add(other.words_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Vendor = input.ReadInt32();
            break;
          }
          case 16: {
            Version = input.ReadInt32();
            break;
          }
          case 24: {
            Seqnum = input.ReadInt32();
            break;
          }
          case 32: {
            Uid = input.ReadInt32();
            break;
          }
          case 40: {
            Flag = input.ReadInt32();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Lang = input.ReadInt32();
            break;
          }
          case 64: {
            Starttime = input.ReadInt32();
            break;
          }
          case 72: {
            Offtime = input.ReadInt32();
            break;
          }
          case 82: {
            words_.AddEntriesFrom(input, _repeated_words_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Vendor = input.ReadInt32();
            break;
          }
          case 16: {
            Version = input.ReadInt32();
            break;
          }
          case 24: {
            Seqnum = input.ReadInt32();
            break;
          }
          case 32: {
            Uid = input.ReadInt32();
            break;
          }
          case 40: {
            Flag = input.ReadInt32();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Lang = input.ReadInt32();
            break;
          }
          case 64: {
            Starttime = input.ReadInt32();
            break;
          }
          case 72: {
            Offtime = input.ReadInt32();
            break;
          }
          case 82: {
            words_.AddEntriesFrom(ref input, _repeated_words_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Word : pb::IMessage<Word>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Word> _parser = new pb::MessageParser<Word>(() => new Word());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Word> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgoraSTTSample.Protobuf.STTMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Word() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Word(Word other) : this() {
      text_ = other.text_;
      startMs_ = other.startMs_;
      durationMs_ = other.durationMs_;
      isFinal_ = other.isFinal_;
      confidence_ = other.confidence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Word Clone() {
      return new Word(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_ms" field.</summary>
    public const int StartMsFieldNumber = 2;
    private int startMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StartMs {
      get { return startMs_; }
      set {
        startMs_ = value;
      }
    }

    /// <summary>Field number for the "duration_ms" field.</summary>
    public const int DurationMsFieldNumber = 3;
    private int durationMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DurationMs {
      get { return durationMs_; }
      set {
        durationMs_ = value;
      }
    }

    /// <summary>Field number for the "is_final" field.</summary>
    public const int IsFinalFieldNumber = 4;
    private bool isFinal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsFinal {
      get { return isFinal_; }
      set {
        isFinal_ = value;
      }
    }

    /// <summary>Field number for the "confidence" field.</summary>
    public const int ConfidenceFieldNumber = 5;
    private double confidence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Confidence {
      get { return confidence_; }
      set {
        confidence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Word);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Word other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      if (StartMs != other.StartMs) return false;
      if (DurationMs != other.DurationMs) return false;
      if (IsFinal != other.IsFinal) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Confidence, other.Confidence)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (StartMs != 0) hash ^= StartMs.GetHashCode();
      if (DurationMs != 0) hash ^= DurationMs.GetHashCode();
      if (IsFinal != false) hash ^= IsFinal.GetHashCode();
      if (Confidence != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Confidence);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (StartMs != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartMs);
      }
      if (DurationMs != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DurationMs);
      }
      if (IsFinal != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsFinal);
      }
      if (Confidence != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (StartMs != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartMs);
      }
      if (DurationMs != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DurationMs);
      }
      if (IsFinal != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsFinal);
      }
      if (Confidence != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (StartMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartMs);
      }
      if (DurationMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DurationMs);
      }
      if (IsFinal != false) {
        size += 1 + 1;
      }
      if (Confidence != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Word other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.StartMs != 0) {
        StartMs = other.StartMs;
      }
      if (other.DurationMs != 0) {
        DurationMs = other.DurationMs;
      }
      if (other.IsFinal != false) {
        IsFinal = other.IsFinal;
      }
      if (other.Confidence != 0D) {
        Confidence = other.Confidence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 16: {
            StartMs = input.ReadInt32();
            break;
          }
          case 24: {
            DurationMs = input.ReadInt32();
            break;
          }
          case 32: {
            IsFinal = input.ReadBool();
            break;
          }
          case 41: {
            Confidence = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 16: {
            StartMs = input.ReadInt32();
            break;
          }
          case 24: {
            DurationMs = input.ReadInt32();
            break;
          }
          case 32: {
            IsFinal = input.ReadBool();
            break;
          }
          case 41: {
            Confidence = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
